Measure Selector = 
var _sel = SELECTEDVALUE('_MeasureCatalog'[Metric Name])
return
SWITCH(_sel,
    "Sales - Actual", [0100_Sales - Actual],
    "Sales - Goal (FactSalesQuota)", [0101_Sales - Goal (FactSalesQuota)],
    "Sales - Goal Achievement %", [0102_Sales - Goal Achievement %],
    "Sales - Strategic Plan Goal", [0103_Sales - Strategic Plan Goal],
    "Sales - vs Strategic Plan %", [0104_Sales - vs Strategic Plan %],
    "Units - Actual", [0200_Units - Actual],
    "Units - Goal (FactSalesQuota)", [0201_Units - Goal (FactSalesQuota)],
    "Units - Goal Achievement %", [0202_Units - Goal Achievement %],
    "Units - Store", [0203_Units - Store],
    "Units - Online", [0204_Units - Online],
    "Gross Profit - Actual", [0300_Gross Profit - Actual],
    "Gross Profit - Goal", [0301_Gross Profit - Goal],
    "Gross Profit - Goal Achievement %", [0302_Gross Profit - Goal Achievement %],
    "Gross Margin %", [0303_Gross Margin %],
    "Sales - Store Channel", [0400_Sales - Store Channel],
    "Sales - Online Channel", [0401_Sales - Online Channel],
    "Online Sales % of Total", [0402_Online Sales % of Total],
    "Store Sales % of Total", [0403_Store Sales % of Total],
    "Discounts - Total", [0500_Discounts - Total],
    "Discount Rate % of Sales", [0501_Discount Rate % of Sales],
    "Returns - Total", [0502_Returns - Total],
    "Return Rate % of Sales", [0503_Return Rate % of Sales],
    "Cost of Goods Sold", [0504_Cost of Goods Sold],
    "Customers - Unique", [0600_Customers - Unique],
    "Avg Transaction Value", [0601_Avg Transaction Value],
    "Customer Lifetime Value", [0602_Customer Lifetime Value],
    "Stores - Count", [0603_Stores - Count],
    "Avg Sales per Store", [0604_Avg Sales per Store],
    "Machine - Total Downtime (Hours)", [0700_Machine - Total Downtime (Hours)],
    "Machine - Count with Downtime", [0701_Machine - Count with Downtime],
    "Machine - Avg Downtime per Machine", [0702_Machine - Avg Downtime per Machine],
    "Machine - Outage Incidents", [0703_Machine - Outage Incidents],
    "Machine - Total Maintenance Cost", [0704_Machine - Total Maintenance Cost],
    "Machine - Preventive Maintenance Cost", [0800_Machine - Preventive Maintenance Cost],
    "Machine - Emergency Maintenance Cost", [0801_Machine - Emergency Maintenance Cost],
    "Machine - Preventive % of Total Cost", [0802_Machine - Preventive % of Total Cost],
    "Machine - Emergency % of Total Cost", [0803_Machine - Emergency % of Total Cost],
    "Machine - Cost per Store", [0804_Machine - Cost per Store],
    "Machine - SLA Uptime Goal %", [0805_Machine - SLA Uptime Goal %],
    "Machine - Actual Uptime %", [0806_Machine - Actual Uptime %],
    "Machine - SLA Compliance %", [0807_Machine - SLA Compliance %],
    "HR - Employees Total", [0900_HR - Employees Total],
    "HR - Headcount per Store", [0901_HR - Headcount per Store],
    "HR - Sales per Employee", [0902_HR - Sales per Employee],
    "HR - Units per Employee", [0903_HR - Units per Employee],
    "HR - Productivity Score", [0904_HR - Productivity Score],
    BLANK()
)
