createOrReplace
	ref table FactSalesQuotaDaily
		lineageTag: 2d0b2e63-6d2c-4a3d-b28f-4dd80ebbc148

		column SalesQuotaDailyKey
			dataType: int64
			formatString: 0
			lineageTag: 9747e39d-a7f6-4fde-9cc3-8bce0e8a0bbe
			summarizeBy: count

			annotation SummarizationSetBy = Automatic

		column SalesQuotaKey
			dataType: int64
			formatString: 0
			lineageTag: 5aecbf12-f522-45f6-b28d-4f6a790d1c4b
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column ChannelKey
			dataType: int64
			formatString: 0
			lineageTag: 0ce1f9ce-eec8-4e03-bd55-1db5c96c97c3
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column StoreKey
			dataType: int64
			formatString: 0
			lineageTag: 056d5d0e-cd51-460b-b2ec-5b34b2837ef8
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column ProductKey
			dataType: int64
			formatString: 0
			lineageTag: d8ed84c8-1f7d-4cc0-8c1d-f14d512fcac0
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column DateKey
			dataType: dateTime
			formatString: Long Date
			lineageTag: 83be2f77-1ea0-4a43-b0b1-e2b22934d74c
			summarizeBy: none
			sourceColumn: DateKey

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column CurrencyKey
			dataType: int64
			formatString: 0
			lineageTag: 298db988-b5f1-4ae7-8a5c-5bc359f0e884
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column ScenarioKey
			dataType: int64
			formatString: 0
			lineageTag: 1b7cf1f7-c990-415c-b638-2bcd57958c34
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column SalesQuantityQuota
			dataType: double
			lineageTag: 1f8b4efa-4932-40a6-b2f1-1e1caf2e5722
			summarizeBy: sum

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column SalesAmountQuota
			dataType: double
			lineageTag: 5b78bd07-3743-4583-902c-5f64b4da18d5
			summarizeBy: sum

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column GrossMarginQuota
			dataType: double
			lineageTag: f8a3d124-996b-4b3b-8ff4-ff8aa7d6b18f
			summarizeBy: sum

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		partition FactSalesQuotaDaily = m
			mode: import
			source =
				let
					Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\FactSalesQuota.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesQuotaKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"DateKey", type date}, {"CurrencyKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"SalesQuantityQuota", Int64.Type}, {"SalesAmountQuota", type number}, {"GrossMarginQuota", type number}}),
					#"Added DaysInMonth" = Table.AddColumn(#"Changed Type", "DaysInMonth", each Date.DaysInMonth([DateKey]), Int64.Type),
					#"Added DateList" = Table.AddColumn(#"Added DaysInMonth", "DateList", each List.Dates(Date.StartOfMonth([DateKey]), [DaysInMonth], #duration(1,0,0,0))),
					#"Expanded DateList" = Table.ExpandListColumn(#"Added DateList", "DateList"),
					#"Renamed DateList" = Table.RenameColumns(#"Expanded DateList",{{"DateList", "DateKey"}}),
					#"Distributed Values" = Table.TransformColumns(#"Renamed DateList",{{"SalesQuantityQuota", each _ / [DaysInMonth], type number}, {"SalesAmountQuota", each _ / [DaysInMonth], type number}, {"GrossMarginQuota", each _ / [DaysInMonth], type number}}),
					#"Added SalesQuotaDailyKey" = Table.AddIndexColumn(#"Distributed Values", "SalesQuotaDailyKey", 1, 1, Int64.Type),
					#"Removed DaysInMonth" = Table.RemoveColumns(#"Added SalesQuotaDailyKey", {"DaysInMonth"}),
					#"Changed Type Final" = Table.TransformColumnTypes(#"Removed DaysInMonth",{{"SalesQuotaDailyKey", Int64.Type}, {"SalesQuotaKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"DateKey", type date}, {"CurrencyKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"SalesQuantityQuota", type number}, {"SalesAmountQuota", type number}, {"GrossMarginQuota", type number}})
				in
					#"Changed Type Final"

		annotation PBI_ResultType = Table
