table '_Date Period Selector'
	lineageTag: 9b31be39-8557-4de3-b131-43c0b21f8df0

	column Type
		dataType: string
		lineageTag: 0ab6ae4b-e45a-4375-b484-71d4c8552b01
		summarizeBy: none
		sourceColumn: Type
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 69da2583-f2ce-4d81-8dae-2f89d581e2b4
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition '_Date Period Selector' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WckmsVNJRMlSK1YlWCk9NzQZyjMAc3/y8kgwgzxjMCyxNLCpJLQLyTcD8yNREEMdUKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Order", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Period", "Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

