table DimCurrency
	lineageTag: deca7c45-7659-4ead-aeb6-220b3114a291

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 22a6fc7a-ef17-462c-b2ee-b0c4694f821f
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: eb884ae1-ae74-451c-9adc-9c0e99946203
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column CurrencyDescription
		dataType: string
		lineageTag: 5813931a-1f57-4664-8dcb-1b73157b13ad
		summarizeBy: none
		sourceColumn: CurrencyDescription

		annotation SummarizationSetBy = Automatic

	partition DimCurrency = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\DimCurrency.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CurrencyKey", Int64.Type}, {"CurrencyName", type text}, {"CurrencyDescription", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

