table DimCustomer
	lineageTag: ab08d93b-849a-4d40-8d56-b6569d85cc33

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 2f73be5e-a75a-4785-b523-67de4eec057e
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 3f0895c4-56a9-47d6-93b2-38f3a50e56ba
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 1dea3335-6fec-4b1b-9e23-e3bbf5bd8650
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: ebeb0985-fec1-4f45-b4d9-476287a63d89
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 164f4624-9116-4752-b0d5-d964bfc45241
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: a2c724b1-85c2-456d-a5ca-d3ba1eafe82f
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 898fb610-7643-48cd-9a9e-b1dce13b1b33
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: int64
		formatString: 0
		lineageTag: d30924a5-3fc5-41e4-bcd5-999fced3415a
		summarizeBy: sum
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: e53341f1-2c43-4090-bb79-18cb9f641b35
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: 1593f995-9b8f-4944-a962-33b88f63ba8a
		summarizeBy: sum
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: string
		lineageTag: b898dcff-6013-4708-8003-a649f29808d9
		summarizeBy: none
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 37b9ba22-dc8a-48b8-b549-c2cab5b3787c
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: int64
		formatString: 0
		lineageTag: 95fe703b-fc46-4a72-a995-e131c0459df3
		summarizeBy: sum
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: 56c4d823-df71-4b7a-8740-8f576457525e
		summarizeBy: sum
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\DimCustomer.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"CustomerKey", Int64.Type}, {"GeographyKey", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"YearlyIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"NumberChildrenAtHome", Int64.Type}, {"Education", type text}, {"Occupation", type text}, {"HouseOwnerFlag", Int64.Type}, {"NumberCarsOwned", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{""})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

