table DimMachine
	lineageTag: 2f651469-afda-4959-9967-9661b987b95e

	column MachineKey
		dataType: int64
		formatString: 0
		lineageTag: 37ab0065-f94a-4dc3-b0f8-b96bec308e0f
		summarizeBy: none
		sourceColumn: MachineKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 00486081-1a02-4e7c-b20e-4ddca3c15ed5
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: a375057d-1d29-408e-88fe-cb9c314ba69d
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 24ff7282-45ac-4e01-b115-f135e643b95c
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineDescription
		dataType: string
		lineageTag: 80d84e64-c73f-41f2-92a2-6f1232a13a56
		summarizeBy: none
		sourceColumn: MachineDescription

		annotation SummarizationSetBy = Automatic

	column VendorName
		dataType: string
		lineageTag: 2503697a-a68d-4783-9bdf-55283df85182
		summarizeBy: none
		sourceColumn: VendorName

		annotation SummarizationSetBy = Automatic

	column MachineOS
		dataType: string
		lineageTag: d33153bf-6531-4af5-82ce-6169b57bcd91
		summarizeBy: none
		sourceColumn: MachineOS

		annotation SummarizationSetBy = Automatic

	column MachineSource
		dataType: string
		lineageTag: 2d8debcc-0dec-4b08-a8ad-2c76f4f00265
		summarizeBy: none
		sourceColumn: MachineSource

		annotation SummarizationSetBy = Automatic

	column MachineHardware
		dataType: string
		lineageTag: 01af218c-db3d-475e-8231-462bf2ae7a45
		summarizeBy: none
		sourceColumn: MachineHardware

		annotation SummarizationSetBy = Automatic

	column MachineSoftware
		dataType: string
		lineageTag: 5b9196cb-262e-4e5c-8d0b-2d7accf626cf
		summarizeBy: none
		sourceColumn: MachineSoftware

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 29d5a2ed-2e77-4f43-9e0d-c87f8f546e73
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ServiceStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3a973320-130c-4e62-83b9-04774aed7f4d
		summarizeBy: none
		sourceColumn: ServiceStartDate

		annotation SummarizationSetBy = Automatic

	column DecommissionDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 41e28992-360c-4af5-bc15-8709d43dacb3
		summarizeBy: none
		sourceColumn: DecommissionDate

		annotation SummarizationSetBy = Automatic

	column LastModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2653c958-34b3-4498-9975-797e6276bdd9
		summarizeBy: none
		sourceColumn: LastModifiedDate

		annotation SummarizationSetBy = Automatic

	partition DimMachine = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\DimMachine.csv"),[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"MachineKey", Int64.Type}, {"StoreKey", Int64.Type}, {"MachineType", type text}, {"MachineName", type text}, {"MachineDescription", type text}, {"VendorName", type text}, {"MachineOS", type text}, {"MachineSource", type text}, {"MachineHardware", type text}, {"MachineSoftware", type text}, {"Status", type text}, {"ServiceStartDate", type datetime}, {"DecommissionDate", type datetime}, {"LastModifiedDate", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

