table DimPromotion
	lineageTag: c08eb217-0bc8-4808-80e5-e02ff73173c1

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: f275f521-9a02-4f84-b96e-36d6a7fa2380
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column PromotionName
		dataType: string
		lineageTag: 9bb5d265-0344-4cd8-8c77-cc0d20a0db8a
		summarizeBy: none
		sourceColumn: PromotionName

		annotation SummarizationSetBy = Automatic

	column DiscountPercent
		dataType: double
		lineageTag: f5741e34-9d17-43fe-923e-014a1fb41256
		summarizeBy: sum
		sourceColumn: DiscountPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromotionType
		dataType: string
		lineageTag: 8943abe7-2572-4f3f-8958-62e50c680c08
		summarizeBy: none
		sourceColumn: PromotionType

		annotation SummarizationSetBy = Automatic

	column PromotionCategory
		dataType: string
		lineageTag: 8043d8ef-a471-4ade-a068-e0e41c5d6836
		summarizeBy: none
		sourceColumn: PromotionCategory

		annotation SummarizationSetBy = Automatic

	partition DimPromotion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\DimPromotion.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PromotionKey", Int64.Type}, {"PromotionName", type text}, {"DiscountPercent", type number}, {"PromotionType", type text}, {"PromotionCategory", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

