table DimProductCategory
	lineageTag: a458e833-3ac8-41e8-bb6b-0ea5797d2fed

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 7817c025-21a2-4265-a442-70960c58be7d
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryName
		dataType: string
		lineageTag: c2fcfe99-8d71-4f10-b721-3fd54226ec99
		summarizeBy: none
		sourceColumn: ProductCategoryName

		annotation SummarizationSetBy = Automatic

	partition DimProductCategory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\DimProductCategory.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"ProductCategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

