table FactSalesQuota
	lineageTag: b6555db1-b659-4a61-8f35-0f6b749f4fdb

	column SalesQuotaKey
		dataType: int64
		formatString: 0
		lineageTag: 2257bbb8-a3fa-4611-9862-cf03e904dabf
		summarizeBy: count
		sourceColumn: SalesQuotaKey

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: be6881bd-6494-4c59-8a8e-e9d1f491734b
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 3ed1e21e-9372-46e7-b101-1b3652b3309a
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: dcd3e1ae-a117-4d7e-abe7-948ec58bea5f
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: fdced221-f7e6-4e86-9b99-d1af5d57fbfe
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 65025703-7998-4566-be2d-c5f3d92a6013
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column ScenarioKey
		dataType: int64
		formatString: 0
		lineageTag: 82dab137-e68d-49e3-9927-efdf8547a247
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = Automatic

	column SalesQuantityQuota
		dataType: int64
		formatString: 0
		lineageTag: 76dc7721-af26-408d-932c-617407c42222
		summarizeBy: sum
		sourceColumn: SalesQuantityQuota

		annotation SummarizationSetBy = Automatic

	column SalesAmountQuota
		dataType: double
		lineageTag: e772c679-bdb7-48d0-9781-18ffe0338f09
		summarizeBy: sum
		sourceColumn: SalesAmountQuota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GrossMarginQuota
		dataType: double
		lineageTag: 427d581e-4c71-4a17-b0e3-3ff9feab1160
		summarizeBy: sum
		sourceColumn: GrossMarginQuota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactSalesQuota = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PHUyJo3\OneDrive - NESTLE\Documents\projects\data\contoso\FactSalesQuota.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesQuotaKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"DateKey", type date}, {"CurrencyKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"SalesQuantityQuota", Int64.Type}, {"SalesAmountQuota", type number}, {"GrossMarginQuota", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

