DEFINE
	FUNCTION GetQuarterStart = (_date : DATETIME) =>
		DATE(YEAR(_date), (3*int((MONTH(_date)-1)/3))+1, 1)
		
	FUNCTION GetQuarterNumber = (_date : DATETIME) =>
		int((MONTH(_date)-1)/3)+1

	FUNCTION GetWeekStart = (_date : DATETIME) =>
		_date - WEEKDAY(_date,2) + 1

	FUNCTION GetMeasureDirectionm = (_measure : STRING) =>
		CALCULATE(
			FIRSTNONBLANK(_MeasureCatalog[Direction], 1),
			FILTER(_MeasureCatalog, _MeasureCatalog[Metric Name]=_measure)
		)

	
