DEFINE
	FUNCTION GetQuarterStart = (_date : DATETIME) =>
		DATE(YEAR(_date), (3*int((MONTH(_date)-1)/3))+1, 1)
		
	FUNCTION GetQuarterNumber = (_date : DATETIME) =>
		int((MONTH(_date)-1)/3)+1

	FUNCTION GetWeekStart = (_date : DATETIME) =>
		_date - WEEKDAY(_date,2) + 1

	FUNCTION GetMeasureDirectionm = (_measure : STRING) =>
		CALCULATE(
			FIRSTNONBLANK(_MeasureCatalog[Direction], 1),
			FILTER(_MeasureCatalog, _MeasureCatalog[Metric Name]=_measure)
		)

	

	FUNCTION FormatMeasure = (_measure : STRING) =>
		SWITCH(_measure,
			"Sales - Actual", "#,000",
			"Sales - Goal (FactSalesQuota)", "#,000",
			"Sales - Goal Achievement %", "0.00%",
			"Sales - Strategic Plan Goal","#,000",
			"Sales - vs Strategic Plan %",  "0.00%",
			"Units - Actual", "#,000",
			"Units - Goal (FactSalesQuota)", "#,000",
			"Units - Goal Achievement %",  "0.00%",
			"Units - Store", "#,000",
			"Units - Online", "#,000",
			"Gross Profit - Goal Achievement %",  "0.00%",
			"Gross Margin %",  "0.00%",
			"Sales - Store Channel", "#,000",
			"Sales - Online Channel", "#,000",
			"Online Sales % of Total",  "0.00%",
			"Store Sales % of Total",  "0.00%",
			"Discount Rate % of Sales",  "0.00%",
			"Return Rate % of Sales",  "0.00%",
			"Customers - Unique", "#,000",
			"Stores - Count", "#,000",
			"Machine - Count with Downtime", "#,000",
			"Machine - Outage Incidents", "#,000",
			"Machine - Preventive % of Total Cost",  "0.00%",
			"Machine - SLA Uptime Goal %",  "0.00%",
			"Machine - Actual Uptime %",  "0.00%",
			"Machine - SLA Compliance %",  "0.00%",
			"HR - Employees Total", "#,000",
			"#,000.00"
		)

	FUNCTION ActualPctToGoal = (_actual : NUMERIC, _goal : NUMERIC, _measure: STRING) =>
	VAR __direction = GetMeasureDirectionm(_measure)
	RETURN
	if(__direction="Positive",
		DIVIDE(_actual, _goal, BLANK()),
		2-DIVIDE(_actual, _goal, BLANK())
	)

	FUNCTION ActualVarToGoal = (_actual : NUMERIC, _goal : NUMERIC) =>
		_actual - _goal
	
	FUNCTION VarianceArrow = (_actual : NUMERIC, _goal : NUMERIC, _measure : string) =>
		var __dir = GetMeasureDirectionm(_measure)
		var __var = ActualVarToGoal(_actual, _goal)
		RETURN
		SWITCH(TRUE(),
			__var = 0, UNICHAR(9658),
			__dir = "Positive" && __var > 0, UNICHAR(9650),
			__dir = "Negative" && __var < 0, UNICHAR(9650),
			 UNICHAR(9660)
		)

	FUNCTION VarianceColor = (_actual : NUMERIC, _goal : NUMERIC, _measure : string) =>
		// var __dir = GetMeasureDirectionm(_measure)
		var __var = ActualPctToGoal(_actual, _goal, _measure)
		RETURN
		SWITCH(TRUE(),
			__var >= .95 && __var < 1, "#b3b300",
			__var <.95, "#990000",
			"#009900"
		)